name: loan_approval_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.1.2
  - pip:
      - wandb==0.15.4
      - pandas==2.0.2
      - numpy==1.24.3
      - scikit-learn==1.2.2
      - shap==0.41.0
      - optuna==3.2.0
      - matplotlib==3.7.1
      - seaborn==0.12.2
      - xgboost==1.7.5
      - openpyxl==3.1.2