wandb_version: 1

n_estimators:
  desc: null
  value: 72
max_depth:
  desc: null
  value: 12
min_samples_split:
  desc: null
  value: 51
min_samples_leaf:
  desc: null
  value: 1
model:
  desc: null
  value: RandomForest
prob_threshold:
  desc: null
  value: 0.38
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686501663.612064
    t:
      1:
      - 1
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 4
      - 5
