wandb_version: 1

booster:
  desc: null
  value: dart
lambda:
  desc: null
  value: 1.7790999373420096e-05
alpha:
  desc: null
  value: 1.650512915738041e-08
n_estimators:
  desc: null
  value: 140
max_depth:
  desc: null
  value: 1
eta:
  desc: null
  value: 0.09449482948657142
gamma:
  desc: null
  value: 0.581624252002296
grow_policy:
  desc: null
  value: depthwise
sample_type:
  desc: null
  value: uniform
normalize_type:
  desc: null
  value: forest
rate_drop:
  desc: null
  value: 7.128435904408131e-06
skip_drop:
  desc: null
  value: 2.3196994630533504e-08
objective:
  desc: null
  value: binary:logistic
verbosity:
  desc: null
  value: 0
model:
  desc: null
  value: XGBoost
prob_threshold:
  desc: null
  value: 0.35
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686501801.737026
    t:
      1:
      - 1
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 4
      - 5
